package com.example

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.util.Log
import android.widget.Toast
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.facebook.CallbackManager
import com.facebook.login.LoginManager
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions

data class UserProfile(
    val id: String,
    val name: String,
    val email: String,
    val photoUrl: String,
    val provider: String // "Google" or "Facebook"
)

object AuthManager {
    var currentUser by mutableStateOf<UserProfile?>(null)
    
    // Official SDK fields
    lateinit var callbackManager: CallbackManager
    lateinit var googleSignInClient: GoogleSignInClient

    private const val PREFS_NAME = "cosmic_striker_prefs"

    fun init(context: Context) {
        callbackManager = CallbackManager.Factory.create()
        
        // Initialize Firebase safely
        var isInitialized = false
        try {
            val app = FirebaseApp.initializeApp(context)
            if (app != null) {
                isInitialized = true
            }
        } catch (e: Exception) {
            Log.e("AuthManager", "FirebaseApp auto-init failed with exception", e)
        }

        // Double check if the default instance is actually initialized
        if (!isInitialized) {
            try {
                FirebaseApp.getInstance()
                isInitialized = true
            } catch (e: IllegalStateException) {
                isInitialized = false
            }
        }

        if (!isInitialized) {
            Log.d("AuthManager", "Default FirebaseApp not initialized. Attempting programmatic fallback...")
            try {
                val options = FirebaseOptions.Builder()
                    .setApiKey("AIzaSyFakeKeyPlaceholderForBuild")
                    .setApplicationId("1:1234567890:android:${context.packageName}")
                    .setProjectId("cosmic-striker-fake-project")
                    .build()
                FirebaseApp.initializeApp(context, options)
            } catch (ex: Exception) {
                Log.e("AuthManager", "Programmatic Firebase fallback initialization failed", ex)
            }
        }

        // Dynamically locate default_web_client_id generated by google-services plugin
        var webClientId = ""
        try {
            // 1. Direct compiled R reference lookup (most reliable if in same package/namespace)
            webClientId = context.getString(R.string.default_web_client_id)
        } catch (e: Exception) {
            Log.d("AuthManager", "Direct R.string.default_web_client_id not found/resolved, trying dynamic identifiers", e)
        }

        if (webClientId.isEmpty()) {
            try {
                // 2. Try lookup via resource ID with namespace package ("com.example")
                val resId = context.resources.getIdentifier("default_web_client_id", "string", "com.example")
                if (resId != 0) {
                    webClientId = context.getString(resId)
                }
            } catch (e: Exception) {
                Log.d("AuthManager", "Dynamic lookup under 'com.example' package failed", e)
            }
        }

        if (webClientId.isEmpty()) {
            try {
                // 3. Try lookup via runtime package name (just in case)
                val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
                if (resId != 0) {
                    webClientId = context.getString(resId)
                }
            } catch (e: Exception) {
                Log.e("AuthManager", "Dynamic lookup under runtime package failed", e)
            }
        }

        if (webClientId.isEmpty()) {
            // 4. Hard fallback to the exact client_type = 3 client ID from google-services.json
            webClientId = "248919173506-tpmu598s1mpq0oq1hb8b351n5t9bvae5.apps.googleusercontent.com"
            Log.w("AuthManager", "Falling back to hardcoded Web Client ID: $webClientId")
        } else {
            Log.d("AuthManager", "Successfully loaded Web Client ID: $webClientId")
        }

        // Auditing all configuration parameters at runtime
        val runtimeSHA1 = getCertificateSHA1(context)
        Log.i("FirebaseAuthAudit", "=================== FIREBASE AUTH CONFIG AUDIT ===================")
        Log.i("FirebaseAuthAudit", "Package Name (at runtime): ${context.packageName}")
        Log.i("FirebaseAuthAudit", "Application ID (Build): com.example.cosmicstriker")
        Log.i("FirebaseAuthAudit", "SHA-1 Fingerprint (Programmatic): $runtimeSHA1")
        Log.i("FirebaseAuthAudit", "SHA-1 Fingerprint (Expected): 05:B6:F8:FE:7B:7C:1C:DA:B6:AD:80:E7:3B:43:89:5A:5C:3D:03:67")
        Log.i("FirebaseAuthAudit", "Default Web Client ID (Loaded): $webClientId")
        Log.i("FirebaseAuthAudit", "==================================================================")

        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()

        if (webClientId.isNotEmpty()) {
            gsoBuilder.requestIdToken(webClientId)
        }
        
        googleSignInClient = GoogleSignIn.getClient(context, gsoBuilder.build())

        // Auto-login if previously logged in (via Firebase Auth as single source of truth)
        loadSession(context)
    }

    private fun loadSession(context: Context) {
        val firebaseUser = try {
            FirebaseAuth.getInstance().currentUser
        } catch (e: Exception) {
            Log.e("AuthManager", "Failed to retrieve Firebase currentUser", e)
            null
        }

        if (firebaseUser != null) {
            var provider = "Firebase"
            for (profile in firebaseUser.providerData) {
                if (profile.providerId == "google.com") {
                    provider = "Google"
                    break
                } else if (profile.providerId == "facebook.com") {
                    provider = "Facebook"
                    break
                }
            }
            currentUser = UserProfile(
                id = firebaseUser.uid,
                name = firebaseUser.displayName ?: "Firebase Pilot",
                email = firebaseUser.email ?: "",
                photoUrl = firebaseUser.photoUrl?.toString() ?: "",
                provider = provider
            )
        } else {
            // Check if there's a cached profile from SharedPreferences as secondary fallback
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            val id = prefs.getString("auth_user_id", null)
            val name = prefs.getString("auth_user_name", null)
            val email = prefs.getString("auth_user_email", null)
            val photoUrl = prefs.getString("auth_user_photo", null)
            val provider = prefs.getString("auth_user_provider", null)

            if (id != null && name != null && email != null && photoUrl != null && provider != null) {
                currentUser = UserProfile(id, name, email, photoUrl, provider)
            }
        }
    }

    fun saveSession(context: Context, user: UserProfile) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().apply {
            putString("auth_user_id", user.id)
            putString("auth_user_name", user.name)
            putString("auth_user_email", user.email)
            putString("auth_user_photo", user.photoUrl)
            putString("auth_user_provider", user.provider)
            apply()
        }
        currentUser = user
    }

    fun clearSession(context: Context) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().apply {
            remove("auth_user_id")
            remove("auth_user_name")
            remove("auth_user_email")
            remove("auth_user_photo")
            remove("auth_user_provider")
            apply()
        }
        currentUser = null
    }

    /**
     * Checks if this account qualifies for the 200 bonus coins.
     * Rewards the bonus only ONCE per account, linked using SharedPreferences.
     * Returns true if first-time bonus was rewarded, false otherwise.
     */
    fun checkAndRewardBonus(context: Context, userId: String): Boolean {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val bonusKey = "user_${userId}_bonus_rewarded"
        val alreadyRewarded = prefs.getBoolean(bonusKey, false)
        
        if (!alreadyRewarded) {
            prefs.edit().putBoolean(bonusKey, true).apply()
            return true
        }
        return false
    }

    /**
     * Overloaded sync method for startup check compat.
     */
    fun syncAccountProgress(
        context: Context,
        userId: String,
        currentCoins: Int,
        currentLevel: Int,
        currentEquippedShip: String,
        currentOwnedShips: Set<String>,
        onProgressRestored: (coins: Int, level: Int, equippedShip: String, ownedShips: Set<String>) -> Unit
    ) {
        syncAccountProgress(
            context = context,
            userId = userId,
            currentCoins = currentCoins,
            currentLevel = currentLevel,
            currentEquippedShip = currentEquippedShip,
            currentOwnedShips = currentOwnedShips,
            onNewUserReward = {},
            onProgressRestored = onProgressRestored
        )
    }

    /**
     * Sync user progress state from/to Firestore & SharedPreferences.
     */
    fun syncAccountProgress(
        context: Context,
        userId: String,
        currentCoins: Int,
        currentLevel: Int,
        currentEquippedShip: String,
        currentOwnedShips: Set<String>,
        onNewUserReward: () -> Unit,
        onProgressRestored: (coins: Int, level: Int, equippedShip: String, ownedShips: Set<String>) -> Unit
    ) {
        val db = try {
            FirebaseFirestore.getInstance()
        } catch (e: Exception) {
            Log.e("AuthManager", "Failed to get Firestore instance", e)
            null
        }

        if (db == null) {
            // Fallback to local SharedPreferences if Firestore fails
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            val hasSavedDataKey = "user_${userId}_has_saved_data"
            val hasSavedData = prefs.getBoolean(hasSavedDataKey, false)

            if (hasSavedData) {
                val coins = prefs.getInt("user_${userId}_total_coins", currentCoins)
                val level = prefs.getInt("user_${userId}_highest_unlocked_level", currentLevel)
                val equippedShip = prefs.getString("user_${userId}_equipped_ship_id", currentEquippedShip) ?: currentEquippedShip
                val ownedCsv = prefs.getString("user_${userId}_owned_ships_csv", currentOwnedShips.joinToString(",")) ?: currentOwnedShips.joinToString(",")
                val ownedShips = ownedCsv.split(",").filter { it.isNotEmpty() }.toSet()
                onProgressRestored(coins, level, equippedShip, ownedShips)
            } else {
                // First time local fallback
                val alreadyRewarded = prefs.getBoolean("user_${userId}_bonus_rewarded", false)
                if (!alreadyRewarded) {
                    prefs.edit().putBoolean("user_${userId}_bonus_rewarded", true).apply()
                    onNewUserReward()
                }
                saveAccountProgress(context, userId, currentCoins + (if (!alreadyRewarded) 200 else 0), currentLevel, currentEquippedShip, currentOwnedShips)
                prefs.edit().putBoolean(hasSavedDataKey, true).apply()
            }
            return
        }

        val docRef = db.collection("users").document(userId)
        docRef.get()
            .addOnSuccessListener { document ->
                if (document != null && document.exists()) {
                    // Existing User! Restore progress from Firestore
                    val coins = document.getLong("coins")?.toInt() ?: currentCoins
                    val level = document.getLong("level")?.toInt() ?: currentLevel
                    val equippedShip = document.getString("equippedShip") ?: currentEquippedShip
                    @Suppress("UNCHECKED_CAST")
                    val ownedList = document.get("ownedShips") as? List<String>
                    val ownedShips = ownedList?.toSet() ?: currentOwnedShips

                    // Sync to local SharedPreferences so they are consistent offline
                    val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
                    prefs.edit().putBoolean("user_${userId}_has_saved_data", true).apply()
                    saveAccountProgress(context, userId, coins, level, equippedShip, ownedShips)

                    // Call restore callback to update UI states
                    onProgressRestored(coins, level, equippedShip, ownedShips)
                } else {
                    // Brand New User in Firestore!
                    // Check local SharedPreferences to see if we already marked them as rewarded locally
                    val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
                    val localRewarded = prefs.getBoolean("user_${userId}_bonus_rewarded", false)
                    
                    val giveReward = !localRewarded
                    val finalCoins = if (giveReward) currentCoins + 200 else currentCoins

                    // Save new profile info to Firestore
                    val data = hashMapOf(
                        "coins" to finalCoins,
                        "level" to currentLevel,
                        "equippedShip" to currentEquippedShip,
                        "ownedShips" to currentOwnedShips.toList(),
                        "rewarded" to true
                    )

                    docRef.set(data)
                        .addOnSuccessListener {
                            Log.d("AuthManager", "Successfully saved initial progress to Firestore")
                        }
                        .addOnFailureListener { e ->
                            Log.e("AuthManager", "Failed to save initial progress to Firestore", e)
                        }

                    // Save local SharedPreferences
                    prefs.edit()
                        .putBoolean("user_${userId}_has_saved_data", true)
                        .putBoolean("user_${userId}_bonus_rewarded", true)
                        .apply()
                    saveAccountProgress(context, userId, finalCoins, currentLevel, currentEquippedShip, currentOwnedShips)

                    if (giveReward) {
                        onNewUserReward()
                    }
                }
            }
            .addOnFailureListener { e ->
                Log.e("AuthManager", "Error reading progress from Firestore, falling back to local SharedPreferences", e)
                // If network is offline, use local SharedPreferences as fallback
                val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
                val hasSavedDataKey = "user_${userId}_has_saved_data"
                val hasSavedData = prefs.getBoolean(hasSavedDataKey, false)

                if (hasSavedData) {
                    val coins = prefs.getInt("user_${userId}_total_coins", currentCoins)
                    val level = prefs.getInt("user_${userId}_highest_unlocked_level", currentLevel)
                    val equippedShip = prefs.getString("user_${userId}_equipped_ship_id", currentEquippedShip) ?: currentEquippedShip
                    val ownedCsv = prefs.getString("user_${userId}_owned_ships_csv", currentOwnedShips.joinToString(",")) ?: currentOwnedShips.joinToString(",")
                    val ownedShips = ownedCsv.split(",").filter { it.isNotEmpty() }.toSet()
                    onProgressRestored(coins, level, equippedShip, ownedShips)
                }
            }
    }

    fun saveAccountProgress(
        context: Context,
        userId: String,
        coins: Int,
        level: Int,
        equippedShip: String,
        ownedShips: Set<String>
    ) {
        // 1. Save locally in SharedPreferences
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().apply {
            putInt("user_${userId}_total_coins", coins)
            putInt("user_${userId}_highest_unlocked_level", level)
            putString("user_${userId}_equipped_ship_id", equippedShip)
            putString("user_${userId}_owned_ships_csv", ownedShips.joinToString(","))
            apply()
        }

        // 2. Save to Firestore asynchronously in background (fire and forget)
        try {
            val db = FirebaseFirestore.getInstance()
            val docRef = db.collection("users").document(userId)
            val data = hashMapOf(
                "coins" to coins,
                "level" to level,
                "equippedShip" to equippedShip,
                "ownedShips" to ownedShips.toList()
            )
            docRef.set(data, SetOptions.merge())
                .addOnSuccessListener {
                    Log.d("AuthManager", "Successfully updated progress in Firestore")
                }
                .addOnFailureListener { e ->
                    Log.e("AuthManager", "Failed to update progress in Firestore", e)
                }
        } catch (e: Exception) {
            Log.e("AuthManager", "Firestore getInstance or set failed", e)
        }
    }

    fun getCertificateSHA1(context: Context): String {
        try {
            val packageInfo = if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
                context.packageManager.getPackageInfo(
                    context.packageName,
                    android.content.pm.PackageManager.GET_SIGNING_CERTIFICATES
                )
            } else {
                @Suppress("DEPRECATION")
                context.packageManager.getPackageInfo(
                    context.packageName,
                    android.content.pm.PackageManager.GET_SIGNATURES
                )
            }
            
            val signatures = if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
                packageInfo.signingInfo?.apkContentsSigners
            } else {
                @Suppress("DEPRECATION")
                packageInfo.signatures
            }

            if (signatures != null && signatures.isNotEmpty()) {
                val cert = signatures[0].toByteArray()
                val md = java.security.MessageDigest.getInstance("SHA-1")
                val publicKey = md.digest(cert)
                val hexString = StringBuilder()
                for (i in publicKey.indices) {
                    val appendString = Integer.toHexString(0xFF and publicKey[i].toInt())
                    if (appendString.length == 1) hexString.append("0")
                    hexString.append(appendString)
                    if (i < publicKey.size - 1) hexString.append(":")
                }
                return hexString.toString().uppercase()
            }
        } catch (e: Exception) {
            Log.e("AuthManager", "Error getting SHA-1 programmatically", e)
        }
        return "UNKNOWN"
    }
}
